### ISSUE TITLE
Allow user to specify casbin table name

### ISSUE THREAD

**Issue by jmgoz11** [abqadeer/python-dycasbin#2]
Would you consider adding a feature that allows the casbin table name to be passed into the adapter constructor?
 
Use case:
 
To leverage dycasbin with different models/policies, providing this capability would allow the ability to segregate the policies into different dynamo casbin tables.   
 
Currently, only the casbin_rule table is supported

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
working on this
