### ISSUE TITLE
remove_policy not persisting to DDB

### ISSUE THREAD

**Issue by stickystyle** [abqadeer/python-dycasbin#4]
When using the RBAC API call `delete_roles_for_user`, the policies get removed from the in-memory model, but when pycasbin calls the adaptor's `remove_filtered_policy` (and then `remove_policy`) function, the call to `dynamodb.delete_item` fails to actually delete the policies from DynamoDB because it looks to be building an incorrect MD5 sum of the items. To make it worse, the call to `dynamodb.delete_item` is never checked to see if it actually worked as `remove_policy` always returns `True`.

My fork has a unit test that demonstrates this issue https://github.com/CoreLogicLLC/python-dycasbin/blob/cc9af96f194945a335578aeecb0adba451cecb27/python_dycasbin/test_adapter.py#L98-L130

**Comment by hsluoyz** [comment]
@Zxilly @ffyuanda

**Comment by abqadeer** [comment]
This has been fixed in #5
